### ISSUE TITLE
Make the site scalable 

### ISSUE THREAD

**Issue by nsteward96** [nsteward96/Sovereign#21]
Reinforce the site so that it looks good in all different viewport cases. Currently some things break or don't look good in different viewports, like the jobs/buildings images which repeat.

**Comment by nsteward96** [comment]
Changing the background styles fixes the background repeating problem:
```css
...
.job-display-box, .building-display-box {
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
}
...
```
